### ISSUE TITLE
More dynamic modules file

### ISSUE THREAD

**Issue by Sheogorath-SI** [freifunk-fulda/site-fffd#8]
The modules file[1] won't be able to get merged up to testing and stable branch because the checkout branch is development everywhere. we may should use version branches for fffd-packages.

[1] https://github.com/freifunk-fulda/site-fffd/blob/development/modules#L7

**Comment by fooker** [comment]
I don't realy see the problem here. You have to change the referenced branches only on the first upstream merge (you can do it in the merge commit). After that there will be no change on that file touching that line.

**Comment by fooker** [comment]
Moved to https://github.com/freifunk-fulda/orga/issues/83.
